services:
  django:
    build: .
    container_name: django_app_kiosco
    command: >
      sh -c "python manage.py migrate &&
             python manage.py makemigrations &&
             python manage.py collectstatic --noinput &&
             gunicorn kiosco_crit.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/static
      - ./media:/app/media
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/ || exit 1" ]
      interval: 5s
      retries: 12

  redis:
    image: redis:7
    container_name: redis_cache_kiosco
    ports:
      - "6379:6379"
    networks:
      - app_net

  # node:
  #   build: ./whatsapp_node
  #   container_name: node_whatsapp_kiosco
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./whatsapp_node:/app
  #     - ./media:/app/media
  #     - node_modules:/app/node_modules
  #   restart: unless-stopped
  #   shm_size: '1gb'
  #   cap_add:
  #     - SYS_ADMIN
  #   security_opt:
  #     - seccomp:unconfined
  #   networks:
  #     - app_net

  nginx:
    image: nginx:latest
    container_name: nginx_proxy_kiosco
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - ./media:/app/media
      - ./docs:/app/docs
    depends_on:
      - django
    #     - node
    networks:
      - app_net

  db:
    image: postgres:15
    container_name: postgres_db_kiosco
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  celery_worker:
    build: .
    container_name: celery_worker_kiosco
    command: celery -A kiosco_crit worker --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - ./media:/app/media
    networks:
      - app_net

  celery_beat:
    build: .
    container_name: celery_beat_kiosco
    command: celery -A kiosco_crit beat --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env
    networks:
      - app_net

  docs_builder:
    build:
      context: ./docs
    volumes:
      - .:/app
    container_name: docs_builder_kiosco
    command: sphinx-build -b html /app/docs/source /app/docs/build/html

volumes:
  static_volume:
  media_volume:
  postgres_data:
  node_modules:

networks:
  app_net:
