services:

  django:
    build: ./backend
    container_name: django_app_carnet
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - node
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    networks:
      - whatsapp_net


  node:
    build:
      context: ./whatsapp_node
    container_name: node_whatsapp_carnet
    ports:
      - "3000:3000"
    volumes:
      - ./whatsapp_node:/app
      - /app/node_modules
      - ./backend/media:/app/media
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - whatsapp_net
    shm_size: '1gb'

networks:
  whatsapp_net:
